# Pull gems from RubyGems
source 'https://rubygems.org'

gem 'guard-compass'
gem 'compass'
gem 'guard-livereload'
gem 'singularitygs', '~> 1.2.1'
gem 'toolkit', '>=1.0.0'
gem 'breakpoint', '>=2.0.7'
gem 'sassy-buttons', '0.1.4'
gem 'autoprefixer-rails'
