#!/bin/bash

# remove the local db
drush sql-drop -y

# download the prod db
drush sql:sync @a-fro.live @self

drush cr

# check whether to keep the prod config in place
while :; do
  case $1 in
    -c|--config) CONFIG="YES"
    ;;
    *) break
  esac
  shift
done

if [ "$CONFIG" != "YES" ]; then
  # import local config
  drush cim -y
fi

drush cr

echo "Sync complete."
